WITH FIRST_GEN AS(
SELECT ED.ID FROM ECOLI_DATA ED
WHERE PARENT_ID is NULL),
SECOND_GEN AS (
SELECT ED.ID FROM ECOLI_DATA ED JOIN FIRST_GEN F ON ED.PARENT_ID = F.ID)
SELECT E.ID FROM ECOLI_DATA E JOIN SECOND_GEN S ON E.PARENT_ID = S.ID
ORDER BY E.ID; 