WITH FIRST_GEN AS (
SELECT ID FROM ECOLI_DATA WHERE
PARENT_ID IS NULL),
SECOND_GEN AS (
SELECT ED.ID FROM ECOLI_DATA ED JOIN FIRST_GEN ON ED.PARENT_ID = FIRST_GEN.ID )

SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT ID FROM SECOND_GEN)
ORDER BY ID;