SELECT * FROM (SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as 'SALES_DATE', PRODUCT_ID,USER_ID, SALES_AMOUNT from ONLINE_SALE WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 3
UNION ALL 
SELECT SALES_DATE, PRODUCT_ID,NULL, SALES_AMOUNT from OFFLINE_SALE WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 3) as A ORDER BY SALES_DATE ASC,
PRODUCT_ID ASC, USER_ID ASC;
