-- 코드를 입력하세요
SELECT CC.car_id, CC.car_type, ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100) as `FEE` from CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RR ON CC.car_id =RR.car_id
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON DP.CAR_TYPE = CC.CAR_TYPE
WHERE CC.car_id not in (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
and DURATION_TYPE LIKE '30%'
GROUP BY car_id
HAVING (`FEE` >= 500000 and `FEE` < 2000000) and CC.car_type in ('세단','SUV') 
ORDER BY `FEE` DESC, CC.car_type, car_id DESC; 




