SELECT `RI`.REST_ID, `RI`.REST_NAME, `RI`.FOOD_TYPE, `RI`.FAVORITES, `RI`.ADDRESS as `ADDRESS`,  ROUND(AVG(`RR`.REVIEW_SCORE),2) as`SCORE` FROM REST_REVIEW `RR` LEFT JOIN REST_INFO `RI` ON `RI`.REST_ID = `RR`.REST_ID 
WHERE `ADDRESS` LIKE '서울%' GROUP BY `RI`.REST_ID ORDER BY `SCORE` DESC
,`RI`.FAVORITES DESC;