-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, CASE FREEZER_YN WHEN 'Y' THEN 'Y' WHEN 'N' THEN 'N' ELSE 'N' END as `FREEZER_YN` from FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기도%'
ORDER BY WAREHOUSE_ID;