-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(DISTINCT(OS.USER_ID)) as `PURCHASED_USER`,ROUND(COUNT(DISTINCT(OS.USER_ID)) / (SELECT COUNT(DISTINCT(USER_ID)) from USER_INFO WHERE YEAR(JOINED) = '2021%'),1) FROM USER_INFO UI JOIN ONLINE_SALE OS ON
UI.USER_ID = OS.USER_ID
WHERE UI.USER_ID IN(
SELECT USER_ID FROM USER_INFO
WHERE YEAR(JOINED) = 2021)
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE);