SELECT B.`HOUR`, IFNULL(`COUNT`,0)as `COUNT` FROM (SELECT ROW_NUMBER() OVER (ORDER BY (SELECT 1))-1 as `HOUR` 
FROM ANIMAL_OUTS 
LIMIT 24) as B LEFT JOIN(
select HOUR(DATETIME) as `HOUR`, COUNT(*)as `COUNT` from ANIMAL_OUTS
GROUP BY HOUR(DATETIME)) as A
ON B.`HOUR` = A.`HOUR` 
;

#SELECT HOUR(DATETIME), COUNT(*) from ANIMAL_OUTS GROUP BY HOUR(DATETIME);