SELECT A.HOUR, COUNT(B.DATETIME) as 'COUNT' FROM
(SELECT ROW_NUMBER() OVER (ORDER BY (SELECT 1))-1 as `HOUR` 
FROM ANIMAL_OUTS 
LIMIT 24) as A
LEFT JOIN ANIMAL_OUTS B ON A.HOUR = HOUR(B.DATETIME) 
GROUP BY A.HOUR
;

#SELECT HOUR(DATETIME), COUNT(*) from ANIMAL_OUTS GROUP BY HOUR(DATETIME);

