-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME , SUM(PRICE) as `TOTAL_SALES` FROM USED_GOODS_BOARD UGB JOIN USED_GOODs_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY UGU.USER_ID
HAVING `TOTAL_SALES` >= 700000
ORDER BY `TOTAL_SALES`;