SELECT HE.EMP_NO, HE.EMP_NAME, CASE 
WHEN AVG(SCORE) >= 96 THEN 'S'
WHEN AVG(SCORE) >= 90 THEN 'A'
WHEN AVG(SCORE) >= 80 THEN 'B'
ELSE 'C'
END 'GRADE'
,
CASE 
WHEN AVG(SCORE) >= 96 THEN HE.SAL * (20/100)
WHEN AVG(SCORE) >= 90 THEN HE.SAL * (15/100)
WHEN AVG(SCORE) >= 80 THEN HE.SAL * (10/100)
ELSE 0
END 'BONUS'
FROM HR_DEPARTMENT HD NATURAL JOIN HR_EMPLOYEES HE NATURAL JOIN HR_GRADE HG
GROUP BY HE.EMP_NO ORDER BY EMP_NO;