-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d")as 'REVIEW_DATE' FROM MEMBER_PROFILE natural join REST_REVIEW
WHERE MEMBER_NAME IN
(SELECT MEMBER_NAME FROM MEMBER_PROFILE natural join REST_REVIEW 
group by MEMBER_ID
having count(*) = (SELECT  COUNT(*) as `a` FROM MEMBER_PROFILE natural join REST_REVIEW
group by MEMBER_ID ORDER BY `a` desc limit 1))
ORDER BY REVIEW_DATE, REVIEW_TEXT;