SELECT ED.ID, GENOTYPE, PARENT_GENOTYPE FROM ECOLI_DATA ED
JOIN 
(SELECT ID, GENOTYPE as 'PARENT_GENOTYPE' FROM ECOLI_DATA) as PT 
ON ED.PARENT_ID = PT.ID
WHERE PARENT_GENOTYPE & GENOTYPE = PARENT_GENOTYPE
ORDER BY ED.ID;