-- 코드를 입력하세요




SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) as 'FILE_PATH' FROM USED_GOODS_FILE UGF WHERE BOARD_ID = (SELECT BOARD_ID FROM USED_GOODS_BOARD UGB ORDER BY UGB.VIEWS DESC LIMIT 1) ORDER BY FILE_ID DESC; 
