SELECT CATEGORY, PRICE as `MAX_PRICE`, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN(
SELECT CATEGORY, MAX(PRICE) as `MAX_PRICE` FROM FOOD_PRODUCT
GROUP BY CATEGORY)
and CATEGORY IN ('과자','국','김치','식용유')
ORDER BY `MAX_PRICE` DESC;