SELECT CASE 
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE Name LIKE 'Python%')
and SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%')
THEN 'A'
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME LIKE 'C#')
THEN 'B'
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%' AND NAME NOT LIKE 'Python')
THEN 'C'
END `GRADE`
,
ID, EMAIL FROM DEVELOPERS
WHERE CASE 
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE Name LIKE 'Python%')
and SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%')
THEN 'A'
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME LIKE 'C#')
THEN 'B'
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%' AND NAME NOT LIKE 'Python')
THEN 'C'
END is not NULL
ORDER BY `GRADE`, ID;

#SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%';

#SELECT SUM(CODE) FROM SKILLCODES WHERE Name LIKE 'Python%';

#SELECT SUM(CODE) FROM SKILLCODES WHERE NAME LIKE 'C#';

#SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%' AND NAME NOT LIKE 'Python';